# Generated by Django 5.2 on 2025-06-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sponsor",
            old_name="sponsor_tier",
            new_name="sponsor_tiers",
        ),
    ]
