# Generated by Django 5.2 on 2025-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0002_rename_sponsor_tier_sponsor_sponsor_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description_ko",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description_ko",
            field=models.TextField(blank=True, null=True),
        ),
    ]
