# Generated by Django 5.2 on 2025-06-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_historicalpage_show_bottom_sponsor_banner_and_more"),
        ("event", "0002_alter_event_options_alter_event_name_and_more"),
        ("file", "0001_initial"),
        ("sponsor", "0003_alter_historicalsponsor_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="sponsortier",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="historicalsponsor",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalsponsor",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="historicalsponsor",
            name="description_ko",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="description_ko",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="sponsor_tiers",
        ),
        migrations.RemoveField(
            model_name="sponsortiersponsorrelation",
            name="sponsor_tier",
        ),
        migrations.AddField(
            model_name="historicalsponsor",
            name="sitemap",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.sitemap",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="sitemap",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cms.sitemap"
            ),
        ),
        migrations.AddField(
            model_name="sponsortier",
            name="sponsors",
            field=models.ManyToManyField(through="sponsor.SponsorTierSponsorRelation", to="sponsor.sponsor"),
        ),
        migrations.AddField(
            model_name="sponsortiersponsorrelation",
            name="tier",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="sponsor.sponsortier"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsortier",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalsponsortier",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsortier",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsortier",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="event.event"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="event.event"),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="sponsortier",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sponsortiersponsorrelation",
            name="sponsor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sponsor.sponsor"),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(fields=("event", "name"), name="uq__spsr__name"),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(fields=("event", "name_ko"), name="uq__spsr__name-name_ko"),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(fields=("event", "name_en"), name="uq__spsr__name-name_en"),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(fields=("event", "name"), name="uq__spsr_tier__name"),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(fields=("event", "order"), name="uq__spsr_tier__order"),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(fields=("event", "name_ko"), name="uq__spsr_tier__name-name_ko"),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(fields=("event", "name_en"), name="uq__spsr_tier__name-name_en"),
        ),
        migrations.AddConstraint(
            model_name="sponsortiersponsorrelation",
            constraint=models.UniqueConstraint(fields=("tier", "sponsor"), name="uq__spsr_tier_rel__tier_spsr"),
        ),
    ]
