# Generated by Django 5.2 on 2025-06-17 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_historicalsitemap_hide_sitemap_hide"),
        ("sponsor", "0005_remove_historicalsponsor_sitemap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsponsor",
            name="page",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="page",
        ),
        migrations.AddField(
            model_name="historicalsponsor",
            name="sitemap",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.sitemap",
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="sitemap",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cms.sitemap"
            ),
        ),
    ]
