# Generated by Django 5.2 on 2025-06-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0006_remove_historicalsponsor_page_remove_sponsor_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="sponsor_tiers",
            field=models.ManyToManyField(through="sponsor.SponsorTierSponsorRelation", to="sponsor.sponsortier"),
        ),
    ]
