# Generated by Django 5.2 on 2025-06-20 07:55

import uuid

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_name_alter_event_name_en_and_more"),
        ("sponsor", "0007_sponsor_sponsor_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="event.event")),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorTagRelation",
            fields=[
                (
                    "id",
                    core.fields.UUIDAutoField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sponsor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sponsor.sponsor")),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sponsor.sponsortag")),
            ],
        ),
        migrations.AddField(
            model_name="sponsor",
            name="tags",
            field=models.ManyToManyField(through="sponsor.SponsorTagRelation", to="sponsor.sponsortag"),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(fields=("name",), name="uq__spsr_tag__name"),
        ),
        migrations.AddConstraint(
            model_name="sponsortagrelation",
            constraint=models.UniqueConstraint(fields=("sponsor", "tag"), name="uq__spsr_tag_rel__spsr_tag"),
        ),
    ]
