# Generated by Django 5.2 on 2025-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sponsor", "0009_historicalsponsortag_sponsortag_name_en_and_more")]
    operations = [
        migrations.RemoveField(model_name="historicalsponsor", name="sitemap"),
        migrations.RemoveField(model_name="sponsor", name="sitemap"),
        migrations.AddField(
            model_name="historicalsponsor",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalsponsor",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicalsponsor",
            name="description_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="description_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
