# Generated by Django 5.2 on 2025-06-21 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_name_alter_event_name_en_and_more"),
        ("file", "0001_initial"),
        ("sponsor", "0010_remove_historicalsponsor_sitemap_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sponsor",
            name="uq__spsr__name",
        ),
        migrations.RemoveConstraint(
            model_name="sponsor",
            name="uq__spsr__name-name_ko",
        ),
        migrations.RemoveConstraint(
            model_name="sponsor",
            name="uq__spsr__name-name_en",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortag",
            name="uq__spsr_tag__name",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortag",
            name="uq__spsr_tag__name-name_ko",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortag",
            name="uq__spsr_tag__name-name_en",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortier",
            name="uq__spsr_tier__name",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortier",
            name="uq__spsr_tier__order",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortier",
            name="uq__spsr_tier__name-name_ko",
        ),
        migrations.RemoveConstraint(
            model_name="sponsortier",
            name="uq__spsr_tier__name-name_en",
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("event", "name"), name="uq__spsr__name"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_ko"),
                name="uq__spsr__name-name_ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_en"),
                name="uq__spsr__name-name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uq__spsr_tag__name"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__spsr_tag__name-name_ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__spsr_tag__name-name_en"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("event", "name"), name="uq__spsr_tier__name"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("event", "order"), name="uq__spsr_tier__order"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_ko"),
                name="uq__spsr_tier__name-name_ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_en"),
                name="uq__spsr_tier__name-name_en",
            ),
        ),
    ]
