# Generated by Django 5.2 on 2025-06-22 08:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0011_remove_sponsor_uq__spsr__name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalsponsor",
            name="description_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="description_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
    ]
