# Generated by Django 5.2 on 2025-07-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
        ("sponsor", "0012_alter_historicalsponsor_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="logo_en",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="logo_ko",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"),
        ),
    ]
