# Generated by Django 5.2 on 2025-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0013_sponsor_logo_en_sponsor_logo_ko"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["name", "fixed_at"]},
        ),
        migrations.AddField(
            model_name="historicalsponsor",
            name="fixed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="fixed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
