# Generated by Django 5.2 on 2025-08-05 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sponsor", "0014_alter_sponsor_options_historicalsponsor_fixed_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["name", "-fixed_at"]},
        ),
    ]
