# Generated by Django 5.2 on 2025-08-11 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_name_alter_event_name_en_and_more"),
        ("sponsor", "0015_alter_sponsor_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["-fixed_at", "name"]},
        ),
        migrations.AddIndex(
            model_name="sponsor",
            index=models.Index(fields=["event", "fixed_at"], name="idx__spsr__event_fixed_at"),
        ),
    ]
