# Generated by Django 5.2 on 2025-08-11 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("sponsor", "0016_alter_sponsor_options_and_more")]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["fixed_at", "name"]},
        ),
    ]
