# Generated by Django 6.0.4 on 2026-05-11 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_remove_event_uq__evt__name_name_ko_and_more"),
        ("file", "0001_initial"),
        ("sponsor", "0017_alter_sponsor_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.RemoveConstraint(model_name="sponsor", name="uq__spsr__name-name_ko"),
        migrations.RemoveConstraint(model_name="sponsor", name="uq__spsr__name-name_en"),
        migrations.RemoveConstraint(model_name="sponsortag", name="uq__spsr_tag__name-name_ko"),
        migrations.RemoveConstraint(model_name="sponsortag", name="uq__spsr_tag__name-name_en"),
        migrations.RemoveConstraint(model_name="sponsortier", name="uq__spsr_tier__name-name_ko"),
        migrations.RemoveConstraint(model_name="sponsortier", name="uq__spsr_tier__name-name_en"),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("event", "name_ko"), name="uq__spsr__name-ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("event", "name_en"), name="uq__spsr__name-en"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__spsr_tag__name-ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__spsr_tag__name-en"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_ko"),
                name="uq__spsr_tier__name-ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsortier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_en"),
                name="uq__spsr_tier__name-en",
            ),
        ),
    ]
