class OpenAPITag:
    CMS = "CMS"
    EVENT_PRESENTATION = "Event > Presentation"
    EVENT_SPONSOR = "Event > Sponsor"

    SHOP_USER = "Shop > 고객"
    SHOP_PRODUCT = "Shop > 상품"
    SHOP_CART = "Shop > 장바구니"
    SHOP_ORDER = "Shop > 주문"
    SHOP_ORDER_REFUND = "Shop > 환불"
    SHOP_PORTONE_WEBHOOK = "Shop > PortOne 결제 Webhook"

    ADMIN_ACCOUNT = "Admin > Sign-In & Sign-Out"
    ADMIN_USER = "Admin > User"
    ADMIN_ALLAUTH = "Admin > Allauth"
    ADMIN_CMS = "Admin > CMS"
    ADMIN_PUBLIC_FILE = "Admin > Public File"
    ADMIN_EVENT_EVENT = "Admin > Event > Event"
    ADMIN_EVENT_PRESENTATION = "Admin > Event > Presentation"
    ADMIN_EVENT_SPONSOR = "Admin > Event > Sponsor"
    ADMIN_JSON_SCHEMA = "Admin > JSON Schema"
    ADMIN_MODIFICATION_AUDIT = "Admin > Modification Audit"
    ADMIN_NOTI_EMAIL = "Admin > Notification > Email"
    ADMIN_NOTI_KAKAO_ALIMTALK = "Admin > Notification > Kakao Alimtalk"
    ADMIN_NOTI_SMS = "Admin > Notification > SMS"
    ADMIN_EXT_API_GOOGLE_OAUTH2 = "Admin > External API > Google OAuth2"
    ADMIN_SHOP_ORDER = "Admin > Shop > 주문"
    ADMIN_SHOP_ORDER_REFUND = "Admin > Shop > 환불"
    ADMIN_SHOP_PRODUCT = "Admin > Shop > 상품"
    ADMIN_SHOP_CATEGORY = "Admin > Shop > 카테고리"
    ADMIN_SHOP_TAG = "Admin > Shop > 태그"
    ADMIN_SHOP_REFUND_AUTHORIZER = "Admin > Shop > 환불 승인자"

    PARTICIPANT_PORTAL_USER = "Participant Portal > Sign-In & Sign-Out & My Profile"
    PARTICIPANT_PORTAL_PUBLIC_FILE = "Participant Portal > Public File"
    PARTICIPANT_PORTAL_PRESENTATION = "Participant Portal > Presentation"
    PARTICIPANT_PORTAL_MODIFICATION_AUDIT = "Participant Portal > Modification Audit"

    EXT_REGISTRATION_DESK_API = "EXT: 등록 데스크 API"
    EXT_PATRON_API = "EXT: 개인 후원자 API"
