# Generated by Django 6.0.4 on 2026-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0002_migrate_from_legacy")]
    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="prepared_cart_hash",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="prepared_cart_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalsingleproductcart",
            name="prepared_cart_hash",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalsingleproductcart",
            name="prepared_cart_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="prepared_cart_hash",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="prepared_cart_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="singleproductcart",
            name="prepared_cart_hash",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="singleproductcart",
            name="prepared_cart_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
