# Generated by Django 5.2 on 2025-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-event_start_at", "-event_end_at"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_en",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_ko",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name_en",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name_ko",
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
