# Generated by Django 5.2 on 2025-06-08 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_alter_event_options_alter_event_name_and_more"),
        ("user", "0005_historicaluserext_nickname_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uq__evt__name"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__evt__name-name_ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__evt__name-name_en"
            ),
        ),
    ]
