# Generated by Django 6.0.4 on 2026-05-11 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_name_alter_event_name_en_and_more"),
        ("user", "0009_alter_historicaluserext_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.RemoveConstraint(model_name="event", name="uq__evt__name-name_ko"),
        migrations.RemoveConstraint(model_name="event", name="uq__evt__name-name_en"),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__evt__name-ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__evt__name-en"
            ),
        ),
    ]
