name: pyconkr-backend-local

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  pyconkr-backend-postgres:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql:rw

    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
    - ${DATABASE_PORT}:5432

  pyconkr-backend-redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
    - ${REDIS_PORT:-46379}:6379
