# Generated by Django 6.0.5 on 2026-05-24 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("product", "0002_image_to_publicfile")]
    operations = [
        migrations.RemoveField(model_name="historicalproduct", name="hidden"),
        migrations.RemoveField(model_name="product", name="hidden"),
    ]
