# Generated by Django 6.0.5 on 2026-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("product", "0003_remove_historicalproduct_hidden_and_more")]
    operations = [
        migrations.AddField(
            model_name="historicaloptiongroup",
            name="max_quantity_per_user",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="max_quantity_per_user",
            field=models.IntegerField(default=0),
        ),
    ]
