# Generated by Django 6.0.5 on 2026-05-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("product", "0004_historicaloptiongroup_max_quantity_per_user_and_more")]
    operations = [
        migrations.AddField(
            model_name="historicaloptiongroup",
            name="orderable_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaloptiongroup",
            name="orderable_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaloptiongroup",
            name="visible_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaloptiongroup",
            name="visible_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="orderable_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="orderable_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="visible_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="visible_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="optiongroup",
            index=models.Index(fields=["visible_starts_at", "visible_ends_at"], name="product_opt_visible_c07173_idx"),
        ),
        migrations.AddIndex(
            model_name="optiongroup",
            index=models.Index(
                fields=["orderable_starts_at", "orderable_ends_at"], name="product_opt_orderab_acf6df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["visible_starts_at", "visible_ends_at"], name="product_pro_visible_bbd4b9_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["orderable_starts_at", "orderable_ends_at"], name="product_pro_orderab_cee344_idx"
            ),
        ),
    ]
