# Generated by Django 6.0.5 on 2026-06-03 08:47

from django.db import migrations, models


def _backfill_is_ticket(apps, schema_editor) -> None:
    Category = apps.get_model("product", "Category")
    Category.objects.filter(name__contains="티켓").update(is_ticket=True)


class Migration(migrations.Migration):
    atomic = True
    dependencies = [("product", "0005_historicaloptiongroup_orderable_ends_at_and_more")]
    operations = [
        migrations.AddField(model_name="category", name="is_ticket", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="historicalcategory",
            name="is_ticket",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill_is_ticket, migrations.RunPython.noop),
    ]
