# Generated by Django 6.0.5 on 2026-06-04 23:29

from django.db.migrations import AddField
from django.db.migrations import Migration as DjangoMigration
from django.db.models import ForeignKey
from django.db.models.deletion import DO_NOTHING, PROTECT


class Migration(DjangoMigration):
    dependencies = [
        ("event", "0004_remove_event_uq__evt__name_name_ko_and_more"),
        ("product", "0006_category_is_ticket_historicalcategory_is_ticket"),
    ]
    operations = [
        AddField(
            model_name="category",
            name="event",
            field=ForeignKey(blank=True, null=True, on_delete=PROTECT, to="event.event"),
        ),
        AddField(
            model_name="historicalcategory",
            name="event",
            field=ForeignKey(
                blank=True, db_constraint=False, null=True, on_delete=DO_NOTHING, related_name="+", to="event.event"
            ),
        ),
    ]
