# Generated by Django 6.0.5 on 2026-06-09 05:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_category_event_historicalcategory_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="refundable_ends_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999),
                help_text="환불 가능 마감 시간. null인 경우 환불 불가. 항상 환불 가능한 상품을 만들려면 9999-12-31같은 먼 미래 날짜로 설정해주세요.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="refundable_ends_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999),
                help_text="환불 가능 마감 시간. null인 경우 환불 불가. 항상 환불 가능한 상품을 만들려면 9999-12-31같은 먼 미래 날짜로 설정해주세요.",
                null=True,
            ),
        ),
    ]
