# Generated by Django 5.2 on 2025-06-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_historicalpage_show_bottom_sponsor_banner_and_more"),
        ("event", "0002_alter_event_options_alter_event_name_and_more"),
        ("presentation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpresentation",
            old_name="presentation_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="historicalpresentationcategory",
            old_name="presentation_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="presentation",
            old_name="presentation_categories",
            new_name="categories",
        ),
        migrations.RemoveField(
            model_name="historicalpresentationspeaker",
            name="name",
        ),
        migrations.RemoveField(
            model_name="historicalpresentationspeaker",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="historicalpresentationspeaker",
            name="name_ko",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="presentation_type",
        ),
        migrations.RemoveField(
            model_name="presentationcategory",
            name="presentation_type",
        ),
        migrations.RemoveField(
            model_name="presentationspeaker",
            name="name",
        ),
        migrations.RemoveField(
            model_name="presentationspeaker",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="presentationspeaker",
            name="name_ko",
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="sitemap",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.sitemap",
            ),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="title",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="title_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="sitemap",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cms.sitemap"
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="title",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presentation",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="title_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="type",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="presentation.presentationtype"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presentationcategory",
            name="type",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="presentation.presentationtype"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpresentationcategory",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalpresentationcategory",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationcategory",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationtype",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalpresentationtype",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationtype",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="presentationcategory",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="presentationcategory",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="presentationcategory",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="presentationcategoryrelation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="presentation.presentationcategory"
            ),
        ),
        migrations.AlterField(
            model_name="presentationcategoryrelation",
            name="presentation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="presentation.presentation"),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="presentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="speakers", to="presentation.presentation"
            ),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="event.event"),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="presentationtype",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(fields=("type", "name"), name="uq__prst_cat__type__name"),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(fields=("type", "name_ko"), name="uq__prst_cat__type__name-name_ko"),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(fields=("type", "name_en"), name="uq__prst_cat__type__name-name_en"),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(fields=("event", "name"), name="uq__prst_type__event__name"),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(fields=("event", "name_ko"), name="uq__prst_type__event__name-name_ko"),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(fields=("event", "name_en"), name="uq__prst_type__event__name-name_en"),
        ),
    ]
