# Generated by Django 5.2 on 2025-06-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_historicalpage_show_bottom_sponsor_banner_and_more"),
        ("presentation", "0002_rename_presentation_type_historicalpresentation_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpresentation",
            name="sitemap",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="sitemap",
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.page",
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="page",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cms.page"),
        ),
    ]
