# Generated by Django 5.2 on 2025-06-21 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_name_alter_event_name_en_and_more"),
        ("presentation", "0003_remove_historicalpresentation_sitemap_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="presentationcategory",
            name="uq__prst_cat__type__name",
        ),
        migrations.RemoveConstraint(
            model_name="presentationcategory",
            name="uq__prst_cat__type__name-name_ko",
        ),
        migrations.RemoveConstraint(
            model_name="presentationcategory",
            name="uq__prst_cat__type__name-name_en",
        ),
        migrations.RemoveConstraint(
            model_name="presentationtype",
            name="uq__prst_type__event__name",
        ),
        migrations.RemoveConstraint(
            model_name="presentationtype",
            name="uq__prst_type__event__name-name_ko",
        ),
        migrations.RemoveConstraint(
            model_name="presentationtype",
            name="uq__prst_type__event__name-name_en",
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "name"),
                name="uq__prst_cat__type__name",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "name_ko"),
                name="uq__prst_cat__type__name-name_ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "name_en"),
                name="uq__prst_cat__type__name-name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name"),
                name="uq__prst_type__event__name",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_ko"),
                name="uq__prst_type__event__name-name_ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_en"),
                name="uq__prst_type__event__name-name_en",
            ),
        ),
    ]
