# Generated by Django 5.2 on 2025-06-22 08:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0004_remove_presentationcategory_uq__prst_cat__type__name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalpresentationspeaker",
            name="biography_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="presentationspeaker",
            name="biography_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
    ]
