# Generated by Django 5.2 on 2025-06-22 11:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
        ("presentation", "0005_alter_historicalpresentationspeaker_biography_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpresentation",
            name="page",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="page",
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="description",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="description_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="description_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AddField(
            model_name="historicalpresentationspeaker",
            name="image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="description",
            field=core.models.MarkdownField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="presentation",
            name="description_en",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="description_ko",
            field=core.models.MarkdownField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"
            ),
        ),
        migrations.AddField(
            model_name="presentationspeaker",
            name="image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"
            ),
        ),
    ]
