# Generated by Django 5.2 on 2025-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0006_remove_historicalpresentation_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpresentation",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="summary_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicalpresentation",
            name="summary_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="presentation",
            name="summary_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="presentation",
            name="summary_ko",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
