# Generated by Django 5.2 on 2025-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0008_callforpresentationschedule_room_roomschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpresentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="presentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
