# Generated by Django 5.2 on 2025-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0009_historicalpresentation_slideshow_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpresentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
