# Generated by Django 5.2 on 2025-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0010_alter_historicalpresentation_slideshow_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
