# Generated by Django 5.2 on 2025-07-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0011_room_name_en_room_name_ko"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomschedule",
            name="presentation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="presentation.presentation"),
        ),
    ]
