# Generated by Django 5.2 on 2025-07-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presentation", "0012_alter_roomschedule_presentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomschedule",
            name="presentation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_schedules",
                to="presentation.presentation",
            ),
        ),
    ]
