# Generated by Django 5.2.5 on 2025-08-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("presentation", "0013_alter_roomschedule_presentation")]
    operations = [
        migrations.AddField(
            model_name="historicalpresentation",
            name="public_slideshow_file",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="최종 외부 공개용 발표 자료",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="public_slideshow_file",
            field=models.ForeignKey(
                blank=True,
                help_text="최종 외부 공개용 발표 자료",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpresentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default="", help_text="발표자가 제출한 발표 자료 URL", null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="slideshow_url",
            field=models.URLField(blank=True, default="", help_text="발표자가 제출한 발표 자료 URL", null=True),
        ),
    ]
