# Generated by Django 6.0.4 on 2026-05-11 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_remove_event_uq__evt__name_name_ko_and_more"),
        ("presentation", "0014_historicalpresentation_public_slideshow_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.RemoveConstraint(model_name="presentationcategory", name="uq__prst_cat__type__name-name_ko"),
        migrations.RemoveConstraint(model_name="presentationcategory", name="uq__prst_cat__type__name-name_en"),
        migrations.RemoveConstraint(model_name="presentationtype", name="uq__prst_type__event__name-name_ko"),
        migrations.RemoveConstraint(model_name="presentationtype", name="uq__prst_type__event__name-name_en"),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "name_ko"),
                name="uq__prst_cat__type__name-ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "name_en"),
                name="uq__prst_cat__type__name-en",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_ko"),
                name="uq__prst_type__event__name-ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="presentationtype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("event", "name_en"),
                name="uq__prst_type__event__name-en",
            ),
        ),
    ]
