# Generated by Django 6.0.4 on 2026-05-23 11:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_payment_preparation"),
        ("payment_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("webhook_received", "Webhook received"),
                            ("payment_lookup_succeeded", "Payment lookup succeeded"),
                            ("payment_lookup_failed", "Payment lookup failed"),
                            ("payment_accepted", "Payment accepted"),
                            ("payment_rejected", "Payment rejected"),
                            ("cancel_succeeded", "Cancel succeeded"),
                            ("cancel_failed", "Cancel failed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=128, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("payment_lookup_response", models.JSONField(blank=True, null=True)),
                ("cancel_response", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="order.order",
                    ),
                ),
                (
                    "payment_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="payment_history.paymenthistory",
                    ),
                ),
                (
                    "single_product_cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="order.singleproductcart",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["event_type"], name="payment_his_event_t_5a1989_idx"),
                    models.Index(fields=["reason_code"], name="payment_his_reason__635ccb_idx"),
                ],
            },
        ),
    ]
