# Generated by Django 6.0.5 on 2026-06-06 15:12

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

CONFIRMATION_OF_PARTICIPATION_V1 = r"""<!DOCTYPE html>
<html lang="ko-kr">

<head>
  <meta charset="utf-8" />
  <style>
    @page {
      size: A4;
      margin: 20mm 18mm;
    }

    * {
      box-sizing: border-box;
    }

    body {
      position: relative;
      font-family: "Noto Sans CJK KR", "Noto Sans KR", "Apple SD Gothic Neo", sans-serif;
      color: #1a1a1a;
      font-size: 12pt;
      line-height: 1.5;
    }

    .topbar {
      position: relative;
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      justify-content: center;
      gap: 2mm;
      border-bottom: 2px solid #1a1a1a;
      padding-bottom: 12mm;
      margin-bottom: 12mm;
    }

    .topbar .doc-no {
      color: #555;
      font-size: 10pt;
    }

    .topbar .titles {
      text-align: center;
      align-self: center;
    }

    .topbar h1 {
      font-size: 36pt;
      margin: 0;
      letter-spacing: 0.1em;
    }

    .topbar .subtitle {
      font-size: 14pt;
      color: #555;
      letter-spacing: 0.1em;
    }

    .qr {
      height: 32mm;
      width: 32mm;
      position: absolute;
      display: flex;
      align-items: center;
      justify-content: center;
      right: 0;
      top: 0;
      border: 1px solid #bdbdbd;
      border-radius: 2mm;
      text-align: center;
    }

    .qr img {
      width: 30mm;
      height: 30mm;
    }

    .qr .label {
      position: absolute;
      left: 50%;
      bottom: 0;
      padding: 0 2mm;
      transform: translate(-50%, 50%);
      background: #fff;
      font-size: 8pt;
      color: #555;
      white-space: nowrap;
    }

    table.fields {
      width: 100%;
      border-collapse: collapse;
    }

    table.fields th,
    table.fields td {
      height: 16mm;
      border: 1px solid #cfcfcf;
      padding: 4mm;
      text-align: left;
      vertical-align: middle;
    }

    table.fields th {
      width: 32%;
      background: #f5f5f5;
      font-weight: bold;
    }

    table.fields th .en {
      font-weight: normal;
      color: #777;
    }

    .footer {
      position: absolute;
      left: 0;
      right: 0;
      bottom: 24mm;
      display: flex;
      flex-direction: column;
      gap: 8mm;
      text-align: center;
    }

    .statement .en {
      display: inline-block;
      margin-top: 2mm;
      font-size: 8pt;
      color: #444;
    }

    .issuer {
      position: relative;
      text-align: center;
    }

    .issuer .issued-at {
      color: #333;
      margin-bottom: 4mm;
    }

    .issuer .org {
      font-size: 24pt;
      font-weight: bold;
      letter-spacing: 0.05em;
    }

    .issuer .stamp {
      position: absolute;
      bottom: 0;
      height: 24mm;
      margin-left: -13mm;
      mix-blend-mode: multiply;
    }
  </style>
</head>

<body>
  <div class="topbar">
    <div class="doc-no">문서번호: {{ document_number }}</div>
    <div class="titles">
      <h1>참 가 확 인 서</h1>
      <div class="subtitle">Confirmation of Participation</div>
    </div>
    <div class="qr">
      <img src="{{ qr_data_uri }}" alt="검증 QR 코드" />
      <span class="label">검증 QR 코드</span>
    </div>
  </div>

  <table class="fields">
    <tr>
      <th>참가자명 <span class="en">(Name)</span></th>
      <td>{{ participant_name }}</td>
    </tr>
    {% if organization %}<tr>
      <th>소속 <span class="en">(Organization)</span></th>
      <td>{{ organization }}</td>
    </tr>{% endif %}
    {% if email %}<tr>
      <th>이메일 <span class="en">(Email)</span></th>
      <td>{{ email }}</td>
    </tr>{% endif %}
    <tr>
      <th>행사명 <span class="en">(Event name)</span></th>
      <td>{{ event_name }}{% if event_name_en %} ({{ event_name_en }}){% endif %}</td>
    </tr>
    <tr>
      <th>행사 일시 <span class="en">(Event date)</span></th>
      <td>{{ event_date }}</td>
    </tr>
  </table>

  <div class="footer">
    <p class="statement">위 사람이 상기 행사에 참가하였음을 확인합니다.<br />
      <span class="en">This certifies that the individual named above has successfully
        participated in the event described above.</span>
    </p>

    <div class="issuer">
      <div class="issued-at">{{ issued_at }}</div>
      <span class="org">사단법인 파이썬사용자모임</span>
      <img class="stamp" src="{{ "document/assets/confirmation_of_participation_stamp.png"|data_uri }}" alt="직인" />
    </div>
  </div>
</body>

</html>
"""


def seed_template(apps, schema_editor):
    DocumentTemplate = apps.get_model("document", "DocumentTemplate")
    DocumentTemplate.objects.update_or_create(
        document_type="confirmation_of_participation",
        defaults={"body": CONFIRMATION_OF_PARTICIPATION_V1},
    )


def unseed_template(apps, schema_editor):
    DocumentTemplate = apps.get_model("document", "DocumentTemplate")
    DocumentTemplate.objects.filter(document_type="confirmation_of_participation").delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(choices=[("confirmation_of_participation", "참가확인서")], max_length=50),
                ),
                ("body", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDocumentTemplate",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(choices=[("confirmation_of_participation", "참가확인서")], max_length=50),
                ),
                ("body", models.TextField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical document template",
                "verbose_name_plural": "historical document templates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIssuedDocument",
            fields=[
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("issuable_object_id", models.UUIDField()),
                ("context", models.JSONField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issuable_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="document.documenttemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical issued document",
                "verbose_name_plural": "historical issued documents",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IssuedDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("issuable_object_id", models.UUIDField()),
                ("context", models.JSONField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issuable_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="contenttypes.contenttype"),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="document.documenttemplate"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("document_type",),
                name="uniq_active_document_template_type",
            ),
        ),
        migrations.AddIndex(
            model_name="issueddocument",
            index=models.Index(
                fields=["issuable_content_type", "issuable_object_id"], name="document_is_issuabl_c2a642_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="issueddocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("issuable_content_type", "issuable_object_id"),
                name="uniq_active_issued_document_per_issuable",
            ),
        ),
        migrations.RunPython(seed_template, unseed_template),
    ]
