# Generated by Django 5.2 on 2025-04-19 07:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=False)),
                ("css", models.TextField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ko", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("subtitle", models.CharField(max_length=512)),
                ("subtitle_ko", models.CharField(max_length=512, null=True)),
                ("subtitle_en", models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.IntegerField(default=0)),
                ("css", models.TextField(blank=True, default=None, null=True)),
                ("body", models.TextField(help_text="Content of the page, Written in markdown format")),
                ("body_ko", models.TextField(help_text="Content of the page, Written in markdown format", null=True)),
                ("body_en", models.TextField(help_text="Content of the page, Written in markdown format", null=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cms.page")),
            ],
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("name_ko", models.CharField(max_length=256, null=True)),
                ("name_en", models.CharField(max_length=256, null=True)),
                ("order", models.IntegerField(default=0)),
                ("display_start_at", models.DateTimeField(blank=True, null=True)),
                ("display_end_at", models.DateTimeField(blank=True, null=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="cms.page")),
                (
                    "parent_sitemap",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cms.sitemap",
                    ),
                ),
            ],
        ),
    ]
