# Generated by Django 5.2 on 2025-05-07 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_historicalpage_historicalsection_historicalsitemap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsitemap",
            name="order",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="sitemap",
            name="order",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
