# Generated by Django 5.2 on 2025-05-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_alter_section_options_alter_sitemap_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitemap",
            name="route_code",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitemap",
            name="route_code",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
