# Generated by Django 5.2 on 2025-05-18 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_historicalsitemap_route_code_sitemap_route_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemap",
            name="parent_sitemap",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="cms.sitemap",
            ),
        ),
    ]
