# Generated by Django 5.2 on 2025-06-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0006_alter_sitemap_parent_sitemap")]
    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="show_bottom_sponsor_banner",
            field=models.BooleanField(default=False, help_text="페이지 하단에 스폰서 배너를 표시할지 여부"),
        ),
        migrations.AddField(
            model_name="historicalpage",
            name="show_top_title_banner",
            field=models.BooleanField(default=False, help_text="페이지 상단에 타이틀 배너를 표시할지 여부"),
        ),
        migrations.AddField(
            model_name="page",
            name="show_bottom_sponsor_banner",
            field=models.BooleanField(default=False, help_text="페이지 하단에 스폰서 배너를 표시할지 여부"),
        ),
        migrations.AddField(
            model_name="page",
            name="show_top_title_banner",
            field=models.BooleanField(default=False, help_text="페이지 상단에 타이틀 배너를 표시할지 여부"),
        ),
    ]
