# Generated by Django 5.2 on 2025-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_historicalpage_show_bottom_sponsor_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitemap",
            name="hide",
            field=models.BooleanField(default=False, help_text="이 Sitemap을 숨길지 여부"),
        ),
        migrations.AddField(
            model_name="sitemap",
            name="hide",
            field=models.BooleanField(default=False, help_text="이 Sitemap을 숨길지 여부"),
        ),
    ]
