# Generated by Django 5.2 on 2025-06-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_historicalsitemap_hide_sitemap_hide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitemap",
            name="external_link",
            field=models.URLField(
                blank=True, help_text="외부 링크인 경우 Page를 지정하는 대신 URL을 입력하세요.", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsitemap",
            name="is_frontend_page",
            field=models.BooleanField(
                default=False, help_text="만약 이 Sitemap이 프론트엔드에 하드코딩된 페이지라면 체크하세요."
            ),
        ),
        migrations.AddField(
            model_name="sitemap",
            name="external_link",
            field=models.URLField(
                blank=True, help_text="외부 링크인 경우 Page를 지정하는 대신 URL을 입력하세요.", null=True
            ),
        ),
        migrations.AddField(
            model_name="sitemap",
            name="is_frontend_page",
            field=models.BooleanField(
                default=False, help_text="만약 이 Sitemap이 프론트엔드에 하드코딩된 페이지라면 체크하세요."
            ),
        ),
        migrations.AlterField(
            model_name="historicalsitemap",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Sitemap 클릭 시 보여질 Page",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cms.page",
            ),
        ),
        migrations.AlterField(
            model_name="sitemap",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Sitemap 클릭 시 보여질 Page",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.page",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitemap",
            constraint=models.UniqueConstraint(
                fields=("parent_sitemap", "route_code"), name="uq__sitemap__parent_route_code"
            ),
        ),
    ]
