# Generated by Django 5.2 on 2025-06-21 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_historicalsitemap_external_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsitemap",
            name="is_frontend_page",
        ),
        migrations.RemoveField(
            model_name="sitemap",
            name="is_frontend_page",
        ),
    ]
