# Generated by Django 5.2 on 2025-06-21 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_remove_historicalsitemap_is_frontend_page_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sitemap",
            name="uq__sitemap__parent_route_code",
        ),
        migrations.AddConstraint(
            model_name="sitemap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("parent_sitemap", "route_code"),
                name="uq__sitemap__parent_route_code",
            ),
        ),
    ]
