# Generated by Django 5.2 on 2025-06-22 08:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_remove_sitemap_uq__sitemap__parent_route_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsection",
            name="body",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format"),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="body_en",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format", null=True),
        ),
        migrations.AlterField(
            model_name="historicalsection",
            name="body_ko",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format", null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="body",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format"),
        ),
        migrations.AlterField(
            model_name="section",
            name="body_en",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format", null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="body_ko",
            field=core.models.MarkdownField(help_text="Content of the page, Written in markdown format", null=True),
        ),
    ]
