# Generated by Django 5.2 on 2025-05-24 14:30
import typing
import uuid

from core.const.system import SYSTEM_EMAIL, SYSTEM_ID, SYSTEM_USERNAME
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

if typing.TYPE_CHECKING:
    from user.models import UserExt as UserExtType


def create_superuser(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    UserExt: type["UserExtType"] = apps.get_model("user", "UserExt")

    if not UserExt.objects.filter(id=SYSTEM_ID).exists():
        UserExt.objects.create_superuser(
            id=SYSTEM_ID,
            username=SYSTEM_USERNAME,
            email=SYSTEM_EMAIL,
            password=uuid.uuid4().hex,
        )


class Migration(migrations.Migration):
    dependencies = [("user", "0001_initial")]
    operations = [migrations.RunPython(create_superuser, migrations.RunPython.noop)]
