# Generated by Django 5.2 on 2025-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_organization_historicalorganization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserext",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Designates whether this user should be treated as active. "
                    "Unselect this instead of deleting accounts."
                ),
                verbose_name="active",
            ),
        ),
    ]
