# Generated by Django 5.2 on 2025-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0005_historicaluserext_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganization",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorganization",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserext",
            name="nickname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserext",
            name="nickname_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="historicaluserext",
            name="nickname_ko",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_ko",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="userext",
            name="nickname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="userext",
            name="nickname_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="userext",
            name="nickname_ko",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name",), name="uq__org__name"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__org__name-name_ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__org__name-name_en"
            ),
        ),
        migrations.AddConstraint(
            model_name="userext",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("nickname__isnull", False)),
                fields=("nickname",),
                name="uq__userext__nickname",
            ),
        ),
        migrations.AddConstraint(
            model_name="userext",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("nickname__isnull", False)),
                fields=("nickname_ko",),
                name="uq__userext__nickname-nickname_ko",
            ),
        ),
        migrations.AddConstraint(
            model_name="userext",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("nickname__isnull", False)),
                fields=("nickname_en",),
                name="uq__userext__nickname-nickname_en",
            ),
        ),
    ]
