# Generated by Django 5.2 on 2025-06-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0001_initial"),
        ("user", "0006_alter_historicalorganization_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserext",
            name="image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="file.publicfile",
            ),
        ),
        migrations.AddField(
            model_name="userext",
            name="image",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="file.publicfile"
            ),
        ),
    ]
