# Generated by Django 5.2 on 2025-07-26 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_historicaluserext_image_userext_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userext",
            name="uq__userext__nickname",
        ),
        migrations.RemoveConstraint(
            model_name="userext",
            name="uq__userext__nickname-nickname_ko",
        ),
        migrations.RemoveConstraint(
            model_name="userext",
            name="uq__userext__nickname-nickname_en",
        ),
    ]
