# Generated by Django 6.0.4 on 2026-05-11 04:32

import uuid

from django.db import migrations, models


def backfill_unique_id(apps, schema_editor):
    UserExt = apps.get_model("user", "UserExt")
    for user in UserExt.objects.filter(unique_id__isnull=True).only("id"):
        UserExt.objects.filter(pk=user.pk).update(unique_id=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("file", "0001_initial"),
        ("user", "0008_remove_userext_uq__userext__nickname_and_more"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="historicaluserext",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterModelOptions(
            name="userext",
            options={"ordering": ["-date_joined"], "verbose_name": "user", "verbose_name_plural": "users"},
        ),
        # historicaluserext 는 unique 가 없으므로 한 번에 추가 가능 (default=uuid4 callable 은 INSERT 시 평가)
        migrations.AddField(
            model_name="historicaluserext",
            name="unique_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        # userext.unique_id 는 unique=True 라 3단계로 추가:
        #   (1) default 없는 nullable 컬럼 (PostgreSQL 이 ALTER TABLE 시 single literal 로 default 평가해 모든 행을 같은 값으로 채우는 문제 회피)
        #   (2) RunPython 으로 행마다 uuid4 backfill
        #   (3) NOT NULL + UNIQUE + default=uuid4 적용
        migrations.AddField(
            model_name="userext",
            name="unique_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_unique_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userext",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="userext",
            index=models.Index(fields=["unique_id"], name="userext_unique_id_idx"),
        ),
        # PR A 베이스라인부터 누적된 modeltranslation constraint 이름 패턴 변경 (`*_name_ko` → `*-ko`)
        migrations.RemoveConstraint(model_name="organization", name="uq__org__name-name_ko"),
        migrations.RemoveConstraint(model_name="organization", name="uq__org__name-name_en"),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_ko",), name="uq__org__name-ko"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)), fields=("name_en",), name="uq__org__name-en"
            ),
        ),
    ]
