# Generated by Django 6.0.6 on 2026-08-09 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0004_seed_payment_completed_email_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="emailnotificationhistorysentto",
            name="uq_notification_emailnotificationhistorysentto_history_recipient",
        ),
        migrations.RemoveConstraint(
            model_name="nhncloudkakaoalimtalknotificationhistorysentto",
            name="uq_notification_nhncloudkakaoalimtalknotificationhistorysentto_history_recipient",
        ),
        migrations.RemoveConstraint(
            model_name="nhncloudsmsnotificationhistorysentto",
            name="uq_notification_nhncloudsmsnotificationhistorysentto_history_recipient",
        ),
        migrations.AddField(
            model_name="emailnotificationhistorysentto",
            name="dedupe_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nhncloudkakaoalimtalknotificationhistorysentto",
            name="dedupe_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nhncloudsmsnotificationhistorysentto",
            name="dedupe_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="emailnotificationhistorysentto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("history", "recipient", "dedupe_key"),
                name="uq_notification_emailnotificationhistorysentto_history_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="nhncloudkakaoalimtalknotificationhistorysentto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("history", "recipient", "dedupe_key"),
                name="uq_notification_nhncloudkakaoalimtalknotificationhistorysentto_history_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="nhncloudsmsnotificationhistorysentto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("history", "recipient", "dedupe_key"),
                name="uq_notification_nhncloudsmsnotificationhistorysentto_history_recipient",
            ),
        ),
    ]
