# Generated by Django 5.2 on 2025-07-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participant_portal_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodificationaudit",
            name="original_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="modificationaudit",
            name="original_data",
            field=models.JSONField(default=dict),
        ),
    ]
