# Generated by Django 6.0.6 on 2026-08-13 00:46

import datetime
import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import internal_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0006_event_logo_historicalevent_logo"),
        ("product", "0009_historicaloptiongroup_placeholder_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationDeskConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField(default=datetime.date(1, 1, 1))),
                ("end_date", models.DateField(default=datetime.date(9999, 12, 31))),
                ("categories", models.ManyToManyField(related_name="+", to="product.category")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="event.event"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "end_date"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lte", models.F("end_date"))),
                        name="registration_desk_config_period_order",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        expressions=[
                            (
                                internal_api.models.DateRange(
                                    "start_date",
                                    "end_date",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_upper=True),
                                ),
                                "&&",
                            )
                        ],
                        name="registration_desk_config_period_overlap",
                    ),
                ],
            },
        ),
    ]
